features = [ "driver_distance", "driver_avg_trip_distance_per_day", "driver_acceptance_rate", "driver_avg_ride_duration_per_day", "driver_completed_days",]
target = "is_accepted"
test_size = 0.2

[random_forest]
n_estimators = 100
max_depth = 5
n_jobs = -1
random_state = 33
bootstrap = true
class_weight = "balanced"
