features = ["driver_distance","is_weekend","event_hour","driver_avg_ride_duration_per_day", "driver_avg_trip_distance_per_day"]
target = "is_accepted"
test_size = 0.2

[random_forest]
n_estimators = 300
max_depth = 30
n_jobs = -1
random_state = 33
bootstrap = true
class_weight = "balanced"
